### PR TITLE
adding a new env variable that provides an option between sequential …

### PR DESCRIPTION
**Pull request by arjunshenoymec**
…and parallel model training

Including parallelism at the training stage will speed up model training in the event of multiple metrics being passed to the container. 

https://pastebin.com/Z5W2VVHw -  snapshot of sequential run

https://pastebin.com/BQLC8qqy - snapshot of parallel run

### CODE REVIEW

**Review by 4n4nd — CHANGES_REQUESTED** [review]
Hey @arjunshenoymec this looks great, thanks!

I have one request. Would it be possible to set `FLT_PARALLELISM` to a number, which would be the number of metrics being trained in parallel.

For example, `FLT_PARALLELISM=3` would train 3 metrics in parallel.

**Comment by arjunshenoymec** [comment]
> Hey @arjunshenoymec this looks great, thanks!
> 
> I have one request. Would it be possible to set `FLT_PARALLELISM` to a number, which would be the number of metrics being trained in parallel.
> 
> For example, `FLT_PARALLELISM=3` would train 3 metrics in parallel.

Sure. I'll make that change and update the request. There is a slight caveat to this though, we would be able to specify any number of metrics to be trained in parallel (with a default of 1) however, in reality, the maximum number of metrics that can be trained in parallel would be limited by the number of cores provided to the container. I guess we can add that as an instruction if needed.

**Comment by arjunshenoymec** [comment]
https://pastebin.com/LXfMiJt3 -> with parallelism set to 2
https://pastebin.com/1uMmxbFa -> with parallelism set to 1 (default)

**Comment by 4n4nd** [comment]
this looks great! I was able to test it with all the three models that we have. Thanks!

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Comment by 4n4nd** [comment]
@arjunshenoymec would you mind creating another PR to this new flag to the README [here](https://github.com/AICoE/prometheus-anomaly-detector#configurations)?

**Comment by arjunshenoymec** [comment]
Sure, will do :)

**Pull request merged**
