### PR TITLE
Adding LSTM model 

### PR DESCRIPTION
**Pull request by pallekc91**

### CODE REVIEW

**Comment by 4n4nd** [comment]
Some formatting issues that the coala bot found:
```
model_lstm.py
| 105| ············prediction·=·model.predict(data_test.reshape(1,1,self.number_of_features)).flatten()[0]
|    | [NORMAL] PycodestyleBear (E231):
|    | E231 missing whitespace after ','

model_lstm.py
| 107| ············scaled_final_value·=·self.scalar.inverse_transform(curr_pred_value.reshape(1,-1)).flatten()[0]
|    | [NORMAL] PycodestyleBear (E231):
|    | E231 missing whitespace after ','

model_lstm.py
| 119| ························+·(np.std(forecast_values[:i])·*·2)
|    | [NORMAL] PycodestyleBear (E131):
|    | E131 continuation line unaligned for hanging indent

model_lstm.py
| 131| ························-·(np.std(forecast_values[:i])·*·2)
|    | [NORMAL] PycodestyleBear (E131):
|    | E131 continuation line unaligned for hanging indent

model_lstm.py
|   1| import·logging
|    | [NORMAL] PyDocStyleBear:
|    | D100: Missing docstring in public module

model_lstm.py
|  34| ····def·prepare_data(self,·data):
|    | [NORMAL] PyDocStyleBear:
|    | D102: Missing docstring in public method

model_lstm.py
|  50| ····def·get_model(self,·lstm_cell_count,·dense_cell_count):
|    | [NORMAL] PyDocStyleBear:
|    | D102: Missing docstring in public method

model_lstm.py
|  58| ····def·train(self,·metric_data=None,·prediction_duration=15):
|    | [NORMAL] PyDocStyleBear:
|    | D102: Missing docstring in public method
``

**Comment by 4n4nd** [comment]
@pallekc91 A couple more issues
```
model_lstm.py
|  35| ····def·prepare_data(self,·data):
|    | [NORMAL] PyDocStyleBear:
|    | D400: First line should end with a period (not 'M')

model_lstm.py
|  52| ····def·get_model(self,·lstm_cell_count,·dense_cell_count):
|    | [NORMAL] PyDocStyleBear:
|    | D400: First line should end with a period (not 'l')

model_lstm.py
|  61| ····def·train(self,·metric_data=None,·prediction_duration=15):
|    | [NORMAL] PyDocStyleBear:
|    | D400: First line should end with a period (not 'l')```

**Comment by 4n4nd** [comment]
> @4n4nd not sure why the thoth is failing. It has something to do with `fbprophet` do you know what they need to do to pass that check?

@MichaelClifford where do you see the issues with fbprophet? I cannot find it

**Comment by harshad16** [comment]
recheck

**Comment by harshad16** [comment]
recheck

**Comment by 4n4nd** [comment]
@MichaelClifford Could you please review the notebooks?

@pallekc91 @usef-kh I was able to test the `model_lstm.py` and it works :+1: 
The only issue I can see is that the model is being created from scratch for every run. Could you please try to pickle the created model and load it for every new run? I think we discussed about this in one of the meetings. 
Create a new PR for model pickling, once the notebooks are reviewed we can merge this.
yay!

**Comment by usef-kh** [comment]
Hello,

Yes we are aware of that and remember discussing this with you throughout
one of our meetings. We’ll look inti this and get back to you as soon as
possible.

Best,
Yousif

**Comment by MichaelClifford** [comment]
Correct me if I'm wrong, but I think the notebooks aren't part of the application at all and are just here for explanation,right?

Also what is the difference between `notebooks/prometheus_anomaly_detection_lstm_test_ipynb.ipynb` and `notebooks/prometheus_anomaly_detection_finallstm_test_ipynb.ipynb` ? It looks to me like one is just the updated version of the other. if that's the case can you remove the least up-to-date notebook, and only include 1 in this PR?

**Comment by usef-kh** [comment]
Hello,

Yes they are purely for explaining.

They tackle the problem in slightly different ways thats why we decided to
keep both.

We ended up deploying the FinalLSTM one, but left the other one incase you
wanted to have a look at it.

Ofcourse, we could remove it if you’d like.

Best,
Yousif

**Comment by MichaelClifford** [comment]
If they are different, then that's fine to keep them both. :partying_face:

**Pull request merged**
