### PR TITLE
Added some structure and preparing for other work (#1)

### PR DESCRIPTION
**Pull request by P6rguVyrst**
Trying to to change too much in one PR:

    Black
    Add some structure
    Testing for breaking imports
    Move helper functions away from test files
    Define make test to run the tests
    Added test coverage reports to **make test**

### CODE REVIEW

**Comment by durandom** [comment]
recheck

**Comment by goern** [comment]
there seem to be some missing docstrings etc, please use `coala --ci` locally on your branch. coala-bears could be installed as a dev dependency. 

```
Executing section all.python...
[33m[WARNING][0m[15:47:06] PyDocStyleBear: This result has no patch attached.[0m

prometheus_anomaly_detector/__init__.py
|   1| The line belonging to the following result cannot be printed because it refers to a line that doesn't seem to exist in the given file.
|    | [NORMAL] PyDocStyleBear:
|    | D104: Missing docstring in public package
[33m[WARNING][0m[15:47:07] PyDocStyleBear: This result has no patch attached.[0m
[33m[WARNING][0m[15:47:07] PyDocStyleBear: This result has no patch attached.[0m

prometheus_anomaly_detector/utils.py
|   1| """Utility·functions"""
|    | [NORMAL] PyDocStyleBear:
|    | D400: First line should end with a period (not 's')

prometheus_anomaly_detector/utils.py
|   5| def·NaN():·return·np.nan
|    | [NORMAL] PyDocStyleBear:
|    | D103: Missing docstring in public function
[33m[WARNING][0m[15:47:07] PyDocStyleBear: This result has no patch attached.[0m

tests/test_configuration.py
|  20| def·test_metric_time_range(metric_start_time_fixture,·metric_end_time_fixture):
|    | [NORMAL] PyDocStyleBear:
|    | D103: Missing docstring in public function
[33m[WARNING][0m[15:47:07] PyDocStyleBear: This result has no patch attached.[0m
[33m[WARNING][0m[15:47:07] PyDocStyleBear: This result has no patch attached.[0m

tests/test_for_breaking_changes.py
|   1| 
|    | [NORMAL] PyDocStyleBear:
|    | D100: Missing docstring in public module

tests/test_for_breaking_changes.py
|   3| def·test_imports():
|    | [NORMAL] PyDocStyleBear:
|    | D202: No blank lines allowed after function docstring (found 1)
[33m[WARNING][0m[15:47:07] PyDocStyleBear: This result has no patch attached.[0m

conftest.py
|   1| The line belonging to the following result cannot be printed because it refers to a line that doesn't seem to exist in the given file.
|    | [NORMAL] PyDocStyleBear:
|    | D100: Missing docstring in public module
[33m[WARNING][0m[15:47:07] PyDocStyleBear: This result has no patch attached.[0m
[33m[WARNING][0m[15:47:07] PyDocStyleBear: This result has no patch attached.[0m
[33m[WARNING][0m[15:47:07] PyDocStyleBear: This result has no patch attached.[0m

tests/conftest.py
|   1| import·os
|    | [NORMAL] PyDocStyleBear:
|    | D100: Missing docstring in public module

tests/conftest.py
|   7| def·metric_start_time_fixture():
|    | [NORMAL] PyDocStyleBear:
|    | D103: Missing docstring in public function

tests/conftest.py
|  14| def·metric_end_time_fixture():
|    | [NORMAL] PyDocStyleBear:
|    | D103: Missing docstring in public function
```

**Comment by 4n4nd** [comment]
@P6rguVyrst this PR improves on a lot of stuff, could you please create multiple smaller PRs so that reviewing is easier?

**Comment by P6rguVyrst** [comment]
@4n4nd I'm sorry I have taken so long to respond. Multiple PR's sounds good!

This project was something that was brought up with me at my company. Prometheus anomaly detection isn't a priority at work for me for this quarter. But it is for this year. This is also the kind of project I'd be interested in contributing to from my spare time.
I've got a lot of ideas about what I'd like to do to make it better, in my mind. This PR was just a fraction I didn't spend too much time on.

I saw there was some work done on this project at our fork of it, but I'd rather contribute and fix issues I see upstream, rather than maintain an incompatible branch. It's also why I raised the licencing issue...

**Comment by 4n4nd** [comment]
No worries! Thanks for contributing to the project!

**Pull request closed without merging**
