### PR TITLE
added sensitivity option for PAD

### PR DESCRIPTION
**Pull request by saswat0**
This parameter will help in manipulating the sensitivity of the anomaly detection logic

### CODE REVIEW

**Review by chauhankaranraj — CHANGES_REQUESTED** [review]
Thanks for the PR @saswat0, this seems like a great idea :smile: However, I think it might not work as intended in cases where `yhat_lower` or `yhat_upper` is negative. E.g. if `yat_upper=2`, and `yhat_lower=-4`, then setting `confidence=1` gives the range (0, 4) which is smaller than the default range (-6, 2).

One suggestion I have to remedy this is to use `confidence_range` as a multiplier on the interval width instead, and to constrain it to be in (0,2) instead of (-1, 1). 
```python
# width of the upper and lower boundaries
upper_range = yhat_upper - yhat
lower_range = yhat - yhat_lower

# confidence_factor defaults to 1.
# if it's doubled then both upper and lower boundary widths are doubled
if (
    current_value < yhat + confidence_factor*upper_range
) and (
    current_value > yhat - confidence_factor*upper_range
):
    anomaly = 0
```
What do you think?

**Comment by saswat0** [comment]
Thanks for the tip! @chauhankaranraj 
I didn't expect metric values to be negative and hence the notion of yhat_lower going negative didn't strike me either. Thank you for pointing that out!
I've made the changes in the PR

**Comment by chauhankaranraj** [comment]
> Thanks for the tip! @chauhankaranraj 
> I didn't expect metric values to be negative and hence the notion of yhat_lower going negative didn't strike me either. Thank you for pointing that out! (Your proposed method is indeed elegant )
> I've made the changes in the PR

Thanks, the changes look good to me :smile: Could you please squash the two commits into one?
/lgtm

**Review by chauhankaranraj — APPROVED** [review]

**Comment by saswat0** [comment]
I've squashed the commits into one ✌️😄

**Review by chauhankaranraj — APPROVED** [review]
/lgtm

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Comment by afirth** [comment]
Poke? <3
/remove-lifecycle stale

**Pull request closed without merging**
